kind: Pod
apiVersion: v1
metadata:
  name: labels
  labels:
    course: k8s
    trainer: charan
    jenkins.build.url: 'https://jenkins.daws2025.online/expense/job/backend'
spec:
  containers:
  - name: nginx
    image: nginx