kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        # soft limit
        cpu: "100mi"
        memory: "128mi"
      # limits should be atleast or more than requests i.e., hard limit
      limits:
        cpu: "100mi"
        memory: "128mi"