apiVersion: v1
kind: pod
metadata:
  name: pod-ConfigMap
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      valueFrom:
        ConfigMapRef:
          name: daws78s
          key: course
    - name: trainer
      valueFrom:
        ConfigMapRef:
          name: daws78s
          key: trainer