apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course-1
      valueFrom:
        configMapKeyRef:
          name: daws78s
          key: course
    - name: trainer-1
      valueFrom:
        configMapKeyRef:
          name: daws78s
          key: trainer

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-config-ref
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: daws78s