apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  # these labels belongs to replicaset resource
  labels:
    name: frontend1
    project: expense1
    app: nginx1
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend2
      app: nginx2
    # below is the pod defination
  template:
    metadata:
      labels:
        tier: frontend3
        app: nginx3
        project: some-project3
    spec:
      containers:
      - name: nginx
        image: nginx:stable-otel