apiVersion: v1
kind: Replicaset
metadata:
  name: nginx
  # these labels belongs to replicaset resource
  labels:
    name: frontend
    project: expense
    component: frontend
    environment: dev
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      name: frontend
      project: expense
      component: frontend
      environment: dev
    # below is the pod defination
  template:
    metadata:
      labels:
        name: frontend
        project: expense
        component: frontend
        environment: dev
        project: some-project
    spec:
      containers:
      - name: nginx
        image: nginx