apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploment
  # these labels belongs to deplyment resource
  labels:
    name: deployment2
    project: expense2
    component: frontend2
spec:
  # modify replicas according to your case
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
      app: nginx
    # below is the pod defination
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
        extra-key: extra-value
    spec:
      containers:
      - name: nginx
        image: nginx

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    name: frontend
    app: nginx
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port