apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploment
  # these labels belongs to deplyment resource
  labels:
    name: deployment
    project: expense
    component: frontend
    environment: dev
    app: nginx
    tier: deployment
spec:
  # modify replicas according to your case
  replicas: 20
  selector:
    matchLabels:
      tier: deployment
      app: nginx
    # below is the pod defination
  template:
    metadata:
      labels:
        tier: deployment
        app: nginx
        project: some-project
        extra-key: extra-value
    spec:
      containers:
      - name: nginx
        image: nginx:stable-otel