apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: project
            operator: In
            values:
            - expense1
  containers:
  - name: with-node-affinity
    image: nginx

---

apiVersion: v1
kind: Node
metadata:
  name: ip-192-168-57-11.ec2.internal
  labels:
    project: expense1 
