apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: pod-1
    purpose: affinity
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always # keep this as always
  # nodeSelector:
  #   topology.kubernetes.io/zone: us-east-1b
