apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    name: pod-a
    purpose: affinity
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always # keep this as always

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    name: chandu
    purpose: affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - pod-c
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always # keep this as always