apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-claim
spec:
  storageClassName: "expense-ebs" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-dynamic
  labels:
    purpose: ebs-dynamic
    project: expense
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic-claim

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: ebs-dynamic
# spec:
#   selector:
#     purpose: ebs-dynamic
#   ports:
#   - protocol: TCP
#     port: 80 #service-port
#     targetPort: 80 #target-port
#     # nodePort: 32761